### ISSUE TITLE
/functions folder - firebase deploy --only functions 

### ISSUE THREAD

**Issue by 0xigami** [glitch003/NftClub#1]
Hey Chris,

facing a problem with the deployment of the backend (frontend is working fine) at the moment. 
=== Deploying to 'gatehaus-6e1a0'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint .

✔  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled

Error: Error occurred while parsing your function triggers.
TypeError: Cannot read property 'apikey' of undefined

Do you get this error as well lately or seen it before ? Thanks in advanced

**Comment by glitch003** [comment]
Hey, so I have something new and better you can use, but I also figured out your original problem and the solution is at the bottom of this comment.  

You should use the LIT protocol, which is a new protocol I built to make this easier.  If you're doing server side auth for dynamic content, you can use the example code in this repo: https://github.com/LIT-Protocol/lit-minimal-jwt-example

The LIT protocol also supports locking static content without the need for a server.  The SDK that you can use to do it is documented here: https://github.com/LIT-Protocol/lit-js-sdk#readme

---- solution to the actual issue is below ----

Hey, sorry, I forgot to mention that you need to set 2 env vars.   You need a bugsnag.com key for a nodejs project and an infura eth http rpc URL.

```
firebase functions:config:set bugsnag.apikey="put_a_bugsnag+apikey_here" infura.url="put_your_infura_url_here"
```

**Comment by glitch003** [comment]
art.haus looks super cool.  I'm happy to hop on a call if you have any questions, or feel free to ask me here.  I will literally write the code to do what you need for you because I want you to try the LIT protocol :)

**Comment by 0xigami** [comment]
made my day, got it working now. Thanks a lot
